params:
- default_values: [0, 0]
  queue_partition_indices: [2, 4]
- param_values: [-1]
  state_value_observation_probs: [0.1]
- empty_value: [-1]
  values_state_width: [1]
  line_length: [15.0]
  spacecraft_length: [1.0]
  spacecraft_speed: [3.5]
  spacecraft_speed_variance: [3.5]
  upstream_partition: [1]
  upstream_state_value_index: [0]
- empty_value: [-1]
  values_state_width: [1]
  partition_flow_allowed: [0]
  upstream_partition: [2]
  upstream_state_value_index: [0]
- param_values: [-1]
  state_value_observation_probs: [0.1]
- empty_value: [-1]
  values_state_width: [1]
  line_length: [10.0]
  spacecraft_length: [1.0]
  spacecraft_speed: [3.5]
  spacecraft_speed_variance: [3.5]
  upstream_partition: [4]
  upstream_state_value_index: [0]
- empty_value: [-1]
  values_state_width: [1]
  partition_flow_allowed: [0]
  upstream_partition: [5]
  upstream_state_value_index: [0]
- param_values: [-1]
  state_value_observation_probs: [0.1]
- empty_value: [-1]
  values_state_width: [1]
  line_length: [20.0]
  spacecraft_length: [1.0]
  spacecraft_speed: [3.5]
  spacecraft_speed_variance: [3.5]
  upstream_partition: [7]
  upstream_state_value_index: [0]
- empty_value: [-1]
  values_state_width: [1]
  partition_flow_allowed: [0]
  upstream_partition: [8]
  upstream_state_value_index: [0]
- empty_value: [-1]
  connected_incoming_partitions: [3, 6, 9]
- empty_value: [-1]
  values_state_width: [1]
  queue_size: [0]
  line_length: [20.0]
  spacecraft_length: [1.0]
  spacecraft_speed: [3.5]
  spacecraft_speed_variance: [3.5]
  upstream_partition: [10]
  upstream_state_value_index: [0]
- empty_value: [-1]
  values_state_width: [1]
  queue_size: [0]
  line_length: [18.0]
  spacecraft_length: [1.0]
  spacecraft_speed: [3.5]
  spacecraft_speed_variance: [3.5]
  upstream_partition: [10]
  upstream_state_value_index: [1]
init_state_values:
- [0, 0, 0]
- [-1]
- [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
- [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
- [-1]
- [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
- [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
- [-1]
- [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
- [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
- [-1, -1]
- [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
- [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
init_time_value: 0.0
seeds: [0, 111, 563456, 228312, 222, 334, 124, 333, 8654, 777786, 33, 1092, 3340]
state_widths: [3, 1, 10, 10, 1, 10, 10, 1, 10, 10, 2, 10, 10]
state_history_depths: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
timesteps_history_depth: 1