// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: action_state.proto

package simio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionState) Reset() {
	*x = ActionState{}
	mi := &file_action_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionState) ProtoMessage() {}

func (x *ActionState) ProtoReflect() protoreflect.Message {
	mi := &file_action_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionState.ProtoReflect.Descriptor instead.
func (*ActionState) Descriptor() ([]byte, []int) {
	return file_action_state_proto_rawDescGZIP(), []int{0}
}

func (x *ActionState) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_action_state_proto protoreflect.FileDescriptor

const file_action_state_proto_rawDesc = "" +
	"\n" +
	"\x12action_state.proto\"%\n" +
	"\vActionState\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06valuesB\rZ\v./pkg/simiob\x06proto3"

var (
	file_action_state_proto_rawDescOnce sync.Once
	file_action_state_proto_rawDescData []byte
)

func file_action_state_proto_rawDescGZIP() []byte {
	file_action_state_proto_rawDescOnce.Do(func() {
		file_action_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_action_state_proto_rawDesc), len(file_action_state_proto_rawDesc)))
	})
	return file_action_state_proto_rawDescData
}

var file_action_state_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_action_state_proto_goTypes = []any{
	(*ActionState)(nil), // 0: ActionState
}
var file_action_state_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_action_state_proto_init() }
func file_action_state_proto_init() {
	if File_action_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_action_state_proto_rawDesc), len(file_action_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_action_state_proto_goTypes,
		DependencyIndexes: file_action_state_proto_depIdxs,
		MessageInfos:      file_action_state_proto_msgTypes,
	}.Build()
	File_action_state_proto = out.File
	file_action_state_proto_goTypes = nil
	file_action_state_proto_depIdxs = nil
}
