// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: partition_state.proto

package simio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float64              `protobuf:"fixed64,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_partition_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_partition_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_partition_state_proto_rawDescGZIP(), []int{0}
}

func (x *State) GetValues() []float64 {
	if x != nil {
		return x.Values
	}
	return nil
}

type PartitionState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	CumulativeTimesteps float64                `protobuf:"fixed64,1,opt,name=cumulative_timesteps,json=cumulativeTimesteps,proto3" json:"cumulative_timesteps,omitempty"`
	PartitionName       string                 `protobuf:"bytes,2,opt,name=partition_name,json=partitionName,proto3" json:"partition_name,omitempty"`
	State               *State                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PartitionState) Reset() {
	*x = PartitionState{}
	mi := &file_partition_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionState) ProtoMessage() {}

func (x *PartitionState) ProtoReflect() protoreflect.Message {
	mi := &file_partition_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionState.ProtoReflect.Descriptor instead.
func (*PartitionState) Descriptor() ([]byte, []int) {
	return file_partition_state_proto_rawDescGZIP(), []int{1}
}

func (x *PartitionState) GetCumulativeTimesteps() float64 {
	if x != nil {
		return x.CumulativeTimesteps
	}
	return 0
}

func (x *PartitionState) GetPartitionName() string {
	if x != nil {
		return x.PartitionName
	}
	return ""
}

func (x *PartitionState) GetState() *State {
	if x != nil {
		return x.State
	}
	return nil
}

var File_partition_state_proto protoreflect.FileDescriptor

const file_partition_state_proto_rawDesc = "" +
	"\n" +
	"\x15partition_state.proto\"\x1f\n" +
	"\x05State\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x01R\x06values\"\x88\x01\n" +
	"\x0ePartitionState\x121\n" +
	"\x14cumulative_timesteps\x18\x01 \x01(\x01R\x13cumulativeTimesteps\x12%\n" +
	"\x0epartition_name\x18\x02 \x01(\tR\rpartitionName\x12\x1c\n" +
	"\x05state\x18\x03 \x01(\v2\x06.StateR\x05stateB\rZ\v./pkg/simiob\x06proto3"

var (
	file_partition_state_proto_rawDescOnce sync.Once
	file_partition_state_proto_rawDescData []byte
)

func file_partition_state_proto_rawDescGZIP() []byte {
	file_partition_state_proto_rawDescOnce.Do(func() {
		file_partition_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_partition_state_proto_rawDesc), len(file_partition_state_proto_rawDesc)))
	})
	return file_partition_state_proto_rawDescData
}

var file_partition_state_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_partition_state_proto_goTypes = []any{
	(*State)(nil),          // 0: State
	(*PartitionState)(nil), // 1: PartitionState
}
var file_partition_state_proto_depIdxs = []int32{
	0, // 0: PartitionState.state:type_name -> State
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_partition_state_proto_init() }
func file_partition_state_proto_init() {
	if File_partition_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_partition_state_proto_rawDesc), len(file_partition_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_partition_state_proto_goTypes,
		DependencyIndexes: file_partition_state_proto_depIdxs,
		MessageInfos:      file_partition_state_proto_msgTypes,
	}.Build()
	File_partition_state_proto = out.File
	file_partition_state_proto_goTypes = nil
	file_partition_state_proto_depIdxs = nil
}
