# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: partition_state.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'partition_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15partition_state.proto\"\x17\n\x05State\x12\x0e\n\x06values\x18\x01 \x03(\x01\"^\n\x0ePartitionState\x12\x1c\n\x14\x63umulative_timesteps\x18\x01 \x01(\x01\x12\x17\n\x0fpartition_index\x18\x02 \x01(\x03\x12\x15\n\x05state\x18\x03 \x01(\x0b\x32\x06.StateB\rZ\x0b./pkg/simiob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'partition_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013./pkg/simio'
  _globals['_STATE']._serialized_start=25
  _globals['_STATE']._serialized_end=48
  _globals['_PARTITIONSTATE']._serialized_start=50
  _globals['_PARTITIONSTATE']._serialized_end=144
# @@protoc_insertion_point(module_scope)
