params:
- manager_directed_coordinates: [12.0, 0.0]
- manager_directed_coordinates: [21.0, 1.0]
- manager_directed_coordinates: [31.0, 2.0]
- manager_directed_coordinates: [44.0, 3.0]
- manager_directed_coordinates: [53.0, 4.0]
- manager_directed_coordinates: [61.0, 5.0]
- manager_directed_coordinates: [1.0, 0.0]
- manager_directed_coordinates: [80.0, 1.0]
- manager_directed_coordinates: [2.0, 2.0]
- manager_directed_coordinates: [42.0, 3.0]
- {}
- {}
- {}
- {}
- {}
- {}
- {}
- {}
- {}
- {}
- chosen_coordinates: [0.0, 0.0]
  match_noise: [1.0]
init_state_values:
- [12.0, 0.0]
- [21.0, 1.0]
- [31.0, 2.0]
- [44.0, 3.0]
- [53.0, 4.0]
- [61.0, 5.0]
- [1.0, 0.0]
- [80.0, 1.0]
- [2.0, 2.0]
- [42.0, 3.0]
- [10.0, 4.0]
- [7.0, 5.0]
- [9.0, 0.0]
- [17.0, 1.0]
- [20.0, 2.0]
- [55.0, 3.0]
- [80.0, 4.0]
- [30.0, 5.0]
- [38.0, 0.0]
- [73.0, 1.0]
- [0.0, 0.0]
init_time_value: 0.0
seeds: [563, 8312, 111, 24253, 55524, 63, 12, 1, 2253, 524, 1563, 822312, 11211, 23, 24, 6, 2, 1000, 3, 4, 8898]
state_widths: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
state_history_depths: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
timesteps_history_depth: 1