params:
- match_state_partition_index: [20]
  opposition_player_partition_indices: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [0]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [0]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [0]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [0]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [0]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [0]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [0]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [0]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [0]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [0]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [1]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [1]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [1]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [1]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [1]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [1]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [1]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [1]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [1]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- match_state_partition_index: [20]
  opposition_player_partition_indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  player_space_finding_talent: [7]
  player_ball_interaction_speed: [0.5]
  player_ball_interaction_inaccuracy: [0.1]
  team_possession_state_value: [1]
  team_attacking_distance_threshold: [10.0]
  team_defensive_distance_threshold: [10.0]
  player_movement_speed: [0.1]
- max_ball_falling_time: [5.0]
init_state_values:
- [12.0, 0.0, 0.0, 0.0]
- [21.0, 1.0, 0.0, 0.0]
- [31.0, 2.0, 0.0, 0.0]
- [44.0, 3.0, 0.0, 0.0]
- [53.0, 4.0, 0.0, 0.0]
- [61.0, 5.0, 0.0, 0.0]
- [1.0, 0.0, 0.0, 0.0]
- [80.0, 1.0, 0.0, 0.0]
- [2.0, 2.0, 0.0, 0.0]
- [42.0, 3.0, 0.0, 0.0]
- [10.0, 4.0, 0.0, 0.0]
- [7.0, 5.0, 0.0, 0.0]
- [9.0, 0.0, 0.0, 0.0]
- [17.0, 1.0, 0.0, 0.0]
- [20.0, 2.0, 0.0, 0.0]
- [55.0, 3.0, 0.0, 0.0]
- [80.0, 4.0, 0.0, 0.0]
- [30.0, 5.0, 0.0, 0.0]
- [38.0, 0.0, 0.0, 0.0]
- [73.0, 1.0, 0.0, 0.0]
- [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
init_time_value: 0.0
seeds: [563, 8312, 111, 24253, 55524, 63, 12, 1, 2253, 524, 1563, 822312, 11211, 23, 24, 6, 2, 1000, 3, 4, 8898]
state_widths: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 11]
state_history_depths: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
timesteps_history_depth: 1