params:
- line_length: [15.0]
  spacecraft_length: [1.0]
  spacecraft_speed: [3.5]
  spacecraft_speed_variance: [3.5]
  partition_flow_allowed: [0]
  time_to_exit: [0.0]
- line_length: [10.0]
  spacecraft_length: [1.0]
  spacecraft_speed: [3.5]
  spacecraft_speed_variance: [3.5]
  partition_flow_allowed: [0]
  time_to_exit: [0.0]
- line_length: [20.0]
  spacecraft_length: [1.0]
  spacecraft_speed: [3.5]
  spacecraft_speed_variance: [3.5]
  partition_flow_allowed: [0]
  time_to_exit: [0.0]
- connected_incoming_partitions: [0, 2, 4]
- line_length: [18.0]
  spacecraft_length: [1.0]
  spacecraft_speed: [3.5]
  spacecraft_speed_variance: [3.5]
  upstream_partition: [3]
  upstream_value_index: [0]
  partition_flow_allowed: [-1]
  time_to_exit: [0.0]
- line_length: [13.0]
  spacecraft_length: [1.0]
  spacecraft_speed: [3.5]
  spacecraft_speed_variance: [3.5]
  upstream_partition: [3]
  upstream_value_index: [1]
  partition_flow_allowed: [-1]
  time_to_exit: [0.0]
init_state_values:
- [1.0, 0.0, 2.0, 0.0, 0.0]
- [0.0, 0.0, 1.0, 0.0, 0.0]
- [1.0, 0.0, 0.0, 0.0, 0.0]
- [1.0, 0.0]
- [0.0, 0.0, 3.0, 0.0, 0.0]
- [1.0, 0.0, 0.0, 0.0, 0.0]
init_time_value: 0.0
seeds: [563456, 228312, 334, 124, 8654, 777786]
state_widths: [5, 5, 5, 2, 5, 5]
state_history_depths: [50, 50, 50, 1, 50, 50]
timesteps_history_depth: 50